[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_ADMIN_CODE"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
